module.exports = [
    { group: 'Form', show: true, name: 'u-flowable-text', alias: '描述文字' },
    { group: 'Form', show: true, name: 'u-flowable-string', alias: '单行输入' },
    { group: 'Form', show: true, name: 'u-flowable-table', alias: '表格' },
    { group: 'Form', show: true, name: 'u-flowable-textarea', alias: '多行输入' },
    { group: 'Form', show: true, name: 'u-flowable-date-time', alias: '时间' },
    { group: 'Form', show: true, name: 'u-flowable-email', alias: '邮箱' },
    { group: 'Form', show: true, name: 'u-flowable-mobile', alias: '手机号' },
    { group: 'Form', show: true, name: 'u-flowable-number', alias: '数字' },
    { group: 'Form', show: true, name: 'u-flowable-link', alias: '链接' },
    { group: 'Form', show: true, name: 'u-flowable-radios', alias: '单选组' },
    { group: 'Form', show: true, name: 'u-flowable-select', alias: '下拉选择' },
    { group: 'Form', show: true, name: 'u-flowable-checkbox', alias: '多选框' },
    { group: 'Form', show: true, name: 'u-flowable-uploader', alias: '上传' },
    { group: 'Form', show: true, name: 'u-flowable-date-time-range', alias: '时间区间' },
    { group: 'Form', show: true, name: 'u-flowable-image-select', alias: '图片选择' },
    { group: 'Form', show: true, name: 'u-flowable-rich-text', alias: '富文本' },
    { group: 'Form', show: true, name: 'u-flowable-address', alias: '地址' },
    { group: 'Form', show: true, name: 'u-flowable-user', alias: '用户' },
    { group: 'Form', show: true, name: 'u-flowable-department', alias: '部门' },
];
